# Generated by Django 4.2.10 on 2026-05-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='product',
            name='api_product_price_b6b1d7_idx',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='price_usd',
        ),
        migrations.AlterField(
            model_name='product',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, help_text='Price in USD', max_digits=10),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price_usd'], name='api_product_price_u_633367_idx'),
        ),
    ]
