# Generated by Django 4.2.10 on 2026-10-01 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_wholesale_and_sku_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product',
            new_name='api_product_sku_c2e3d4_idx',
            old_name='api_product_sku_b4e912_idx',
        ),
    ]
